### ISSUE TITLE
Error in train images

### ISSUE THREAD

**Issue by appucharan21** [Patelrahul4884/Attendance-Management-system-using-face-recognition#17]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "F:\Project\Attendance-Management-system-using-face-recognition-master\attendance.py", line 268, in train_image
    trainImage.TrainImage(
  File "F:\Project\Attendance-Management-system-using-face-recognition-master\trainImage.py", line 12, in TrainImage
    recognizer = cv2.face.LBPHFaceRecognizer_create()
                 ^^^^^^^^
Attribute Error: module 'cv2' has no attribute 'face'   

pls help me to solve this problem

**Comment by Patelrahul4884** [comment]
Hi @appucharan21 
can you try following command 
`pip install opencv-contrib-python`

**Comment by Arockiamari** [comment]
It's working thank you so much😊

**Comment by Santosh56kumar** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\santosh2\Face_detaction\attendance.py", line 239, in take_image
    takeImage.TakeImage(
  File "c:\Users\santosh2\Face_detaction\takeImage.py", line 30, in TakeImage
    os.mkdir(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\santosh2\\Face_detaction\\TrainingImage\\456_santoh'

please help me to solve this problem
