### ISSUE TITLE
unable to find file "Attendance/subjectname"

### ISSUE THREAD

**Issue by dkv204p** [Patelrahul4884/Attendance-Management-system-using-face-recognition#19]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Dev Verma\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Dev Verma\Documents\FACE-DETECTION-RECOGNITION\automaticAttedance.py", line 226, in Attf
    os.startfile(
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Attendance/subjectname

**Comment by RaushanKum11** [comment]
same problem bro did you solve this oroblem

**Comment by Arockiamari** [comment]
> Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "c:\Users\NAME\Documents\FACE-DETECTION-RECOGNITION\automaticAttedance.py", line 226, in Attf os.startfile( FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Attendance/subjectname
 


> Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "c:\Users\NAME\Documents\FACE-DETECTION-RECOGNITION\automaticAttedance.py", line 226, in Attf os.startfile( FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Attendance/subjectname

Yes... There is nothing... But I have to get that code using chatgpt... Now its working perfectly.... It was good
... You can try it that way

**Comment by dkv204p** [comment]
Bro can you zip your code and send it to me please.

**Comment by dkv204p** [comment]
> > Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "c:\Users\NAME\Documents\FACE-DETECTION-RECOGNITION\automaticAttedance.py", line 226, in Attf os.startfile( FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Attendance/subjectname
>  
> 
> 
> > Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\NAME\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "c:\Users\NAME\Documents\FACE-DETECTION-RECOGNITION\automaticAttedance.py", line 226, in Attf os.startfile( FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Attendance/subjectname
> 
> Yes... There is nothing... But I have to get that code using chatgpt... Now its working perfectly.... It was good
> ... You can try it that way

Can u push it in repo.?

**Comment by Arockiamari** [comment]
You can create a Attendance folder and in to the attendance folder to
create subject folders example... Attendance folder 📂Inside this folder to
create below 3 or more folder like this
1) python folder
2) java folder
3) c++ folder

**Comment by Irfan271** [comment]
Code is already available on that repository you can setup the code
according to the instructions given in the readme file
