### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Umer009** [Patelrahul4884/Attendance-Management-system-using-face-recognition#3]
[ WARN:0] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Mirza Umar\Desktop\FYP-2022\AMSUFR\attendance.py", line 267, in train_image
    trainImage.TrainImage(
  File "C:\Users\Mirza Umar\Desktop\FYP-2022\AMSUFR\trainImage.py", line 12, in TrainImage
    recognizer = cv2.face.LBPHFaceRecognizer.create()
AttributeError: module 'cv2' has no attribute 'face'

i've installed all the libraries and already set the new paths, please let me know what is the issue here.

**Comment by Patelrahul4884** [comment]
try installing the library

`pip install opencv-contrib-python`

**Comment by Umer009** [comment]
Requirement already satisfied: opencv-contrib-python in c:\users\mirza umar\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-
packages\python37\site-packages (4.2.0.34)
Requirement already satisfied: numpy>=1.14.5 in c:\users\mirza umar\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages
\python37\site-packages (from opencv-contrib-python) (1.16.1)

I've already tried this.

**Comment by Umer009** [comment]
What else should I do??
